# Generated by Django 4.1.5 on 2023-01-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=160)),
                ('starting_bid', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='myphotos')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
    ]
