# Generated by Django 4.1.5 on 2023-01-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='current_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
