# Generated by Django 4.1.5 on 2023-01-31 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_user_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_activity',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='user_activity',
            name='current_listing',
        ),
        migrations.AddField(
            model_name='listings',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_activity',
            name='watched',
            field=models.ManyToManyField(blank=True, related_name='watched', to='auctions.listings'),
        ),
        migrations.CreateModel(
            name='Biddings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bid', models.IntegerField()),
                ('listing_bid', models.ManyToManyField(blank=True, related_name='listing_bid', to='auctions.listings')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
