# Generated by Django 4.1.5 on 2023-01-31 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_user_activity_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
