# Generated by Django 4.1.5 on 2023-01-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listings_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='current_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
