# Generated by Django 4.1.5 on 2023-02-01 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listings_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biddings',
            name='listing_bid',
        ),
        migrations.AddField(
            model_name='biddings',
            name='listing_bid',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listing_bid', to='auctions.listings'),
            preserve_default=False,
        ),
    ]
