# Generated by Django 4.1.5 on 2023-02-01 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_biddings_listing_bid_biddings_listing_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=120)),
                ('listing_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_id', to='auctions.listings')),
                ('user_comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
