# Generated by Django 4.1.5 on 2023-02-08 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_biddings_bidding_rename_comments_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_activity',
            name='watched',
        ),
        migrations.AddField(
            model_name='user_activity',
            name='watched',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watched', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
