# Generated by Django 4.1.5 on 2023-02-15 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_category_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
