# Generated by Django 4.1.5 on 2023-02-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='post_date',
        ),
    ]
