# Generated by Django 4.1.5 on 2023-02-15 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_listing_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
