# Generated by Django 4.1.5 on 2023-02-17 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_remove_category_listing_alter_listing_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('listing_closed', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_closed', to='auctions.listing')),
                ('user_closed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_closed', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
