# Generated by Django 4.1.5 on 2023-02-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_alter_listing_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='closed',
            options={'verbose_name_plural': 'Closed Listings'},
        ),
        migrations.AlterModelOptions(
            name='user_activity',
            options={'verbose_name_plural': 'Watched listings'},
        ),
        migrations.AlterField(
            model_name='bidding',
            name='bid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.FloatField(),
        ),
    ]
